////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"
#include "chip_id.h"

#include "csw_map.h"
#include "hal_map_engine.h"

// =============================================================================
//  MACROS
// =============================================================================

#define CSW_VERSION_STRING	"CSW_01.02.04_20091221_221"
#include "cswp_version.h"


// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

// =============================================================================
// g_cswMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_cswMapVersion = CSW_VERSION_STRUCT;



// =============================================================================
// g_cswMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED CSW_MAP_ACCESS_T g_cswMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// csw_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID csw_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_CSW, &g_cswMapVersion, &g_cswMapAccess);
}


