
// all size and laddr defines are given in word size

#define RAM_I_START               (RAM_I_MIN/2) 
#define RAM_I_END                 (RAM_I_MAX/2) 

#define SECTION_1_START (1488/2 + RAM_I_START) 
#define SECTION_2_START (5240/2 + RAM_I_START) 
#define SECTION_3_START (7576/2 + RAM_I_START) 
#define SECTION_4_START (9600/2 + RAM_I_START) 

#define SECTION_COMMON_SIZE        (SECTION_1_START - RAM_I_START) 
#define SECTION_VOCODER_SIZE       (RAM_I_END       - SECTION_1_START) 
#define SECTION_AMR_SPE_SIZE       (SECTION_3_START - SECTION_2_START) 
#define SECTION_AMR_ENC_SIZE       (SECTION_4_START - SECTION_3_START) 
#define SECTION_AMR_DEC_SIZE       (RAM_I_END       - SECTION_4_START) 
#define SECTION_MSDF_SIZE                32

#define SECTION_HR_RAMX_CONTANTS_SIZE     1304
#define SECTION_HR_RAMY_CONTANTS_SIZE     2640 

#define SECTION_AMR_EFR_RAMY_CONTANTS_SIZE     (3352+616)//4128 
#define SECTION_AMR_EFR_RAMX_CONTANTS_SIZE     2792 //2736//3096


#define SECTION_SPEECH_RAMX_BACKUP_SIZE     2000
#define SECTION_SPEECH_CODE_BACKUP_SIZE     3000
#define SECTION_AEC_RAMX_BACKUP_SIZE     2000
#define SECTION_AEC_CODE_SIZE     3000
#define SECTION_AEC_CONSTANTX_SIZE     1000

#define SECTION_SPEECH_RAMY_BACKUP_SIZE     2000
#define SECTION_MORPH_CONSTY_SIZE     1000
#define SECTION_MORPH_CODE_SIZE     2000


#define G_RXBUF_SIZE     160
#define G_TXBUF_SIZE     160






// start of different image sections in extern RAM

#define SECTION1_IMAGE_START       (0)

#define EFR_AMR_START              (SECTION1_IMAGE_START + 0*SECTION_VOCODER_SIZE) 
#define FR_START                   (SECTION1_IMAGE_START + 1*SECTION_VOCODER_SIZE) 
#define HR_START                   (SECTION1_IMAGE_START + 2*SECTION_VOCODER_SIZE) 


#define SECTION2_IMAGE_START       (SECTION1_IMAGE_START + 3*SECTION_VOCODER_SIZE)

#define AMR_START                  (SECTION2_IMAGE_START + 0*SECTION_AMR_SPE_SIZE) 
#define EFR_START                  (SECTION2_IMAGE_START + 1*SECTION_AMR_SPE_SIZE) 

#define SECTION3_IMAGE_START       (SECTION2_IMAGE_START + 2*SECTION_AMR_SPE_SIZE)

#define AMR475_ENC_START           (SECTION3_IMAGE_START + 0*SECTION_AMR_ENC_SIZE) 
#define AMR515_ENC_START           (SECTION3_IMAGE_START + 1*SECTION_AMR_ENC_SIZE) 
#define AMR59_ENC_START            (SECTION3_IMAGE_START + 2*SECTION_AMR_ENC_SIZE) 
#define AMR67_ENC_START            (SECTION3_IMAGE_START + 3*SECTION_AMR_ENC_SIZE) 
#define AMR74_ENC_START            (SECTION3_IMAGE_START + 4*SECTION_AMR_ENC_SIZE) 
#define AMR795_ENC_START           (SECTION3_IMAGE_START + 5*SECTION_AMR_ENC_SIZE) 
#define AMR102_ENC_START           (SECTION3_IMAGE_START + 6*SECTION_AMR_ENC_SIZE) 
#define AMR122_ENC_START           (SECTION3_IMAGE_START + 7*SECTION_AMR_ENC_SIZE) 


#define SECTION4_IMAGE_START       (SECTION3_IMAGE_START + 8*SECTION_AMR_ENC_SIZE)

#define AMR475_DEC_START           (SECTION4_IMAGE_START + 0*SECTION_AMR_DEC_SIZE) 
#define AMR515_DEC_START           (SECTION4_IMAGE_START + 1*SECTION_AMR_DEC_SIZE) 
#define AMR59_DEC_START            (SECTION4_IMAGE_START + 2*SECTION_AMR_DEC_SIZE) 
#define AMR67_DEC_START            (SECTION4_IMAGE_START + 3*SECTION_AMR_DEC_SIZE) 
#define AMR74_DEC_START            (SECTION4_IMAGE_START + 4*SECTION_AMR_DEC_SIZE) 
#define AMR795_DEC_START           (SECTION4_IMAGE_START + 5*SECTION_AMR_DEC_SIZE) 
#define AMR102_DEC_START           (SECTION4_IMAGE_START + 6*SECTION_AMR_DEC_SIZE) 
#define AMR122_DEC_START           (SECTION4_IMAGE_START + 7*SECTION_AMR_DEC_SIZE)

#define SECTION5_IMAGE_START       (SECTION4_IMAGE_START + 8*SECTION_AMR_DEC_SIZE) 
#define MSDF_START                 (SECTION5_IMAGE_START + 0*SECTION_MSDF_SIZE) 


#define HR_RAMX_CONTANTS_START            (SECTION5_IMAGE_START + 1*SECTION_MSDF_SIZE) 
#define HR_RAMY_CONTANTS_START            (HR_RAMX_CONTANTS_START + 1*SECTION_HR_RAMX_CONTANTS_SIZE) 

#define AMR_EFR_RAMY_CONTANTS_START       (HR_RAMY_CONTANTS_START + 1*SECTION_HR_RAMY_CONTANTS_SIZE) 
#define AMR_EFR_RAMX_CONTANTS_START       (AMR_EFR_RAMY_CONTANTS_START + 1*SECTION_AMR_EFR_RAMY_CONTANTS_SIZE)


#define SPEECH_RAMX_BACKUP_START (AMR_EFR_RAMX_CONTANTS_START + 1*SECTION_AMR_EFR_RAMX_CONTANTS_SIZE) 
#define SPEECH_CODE_BACKUP_START (SPEECH_RAMX_BACKUP_START + 1*SECTION_SPEECH_RAMX_BACKUP_SIZE) 
#define AEC_RAMX_BACKUP_START	 (SPEECH_CODE_BACKUP_START + 1*SECTION_SPEECH_CODE_BACKUP_SIZE) 
#define AEC_CODE_START			 (AEC_RAMX_BACKUP_START + 1*SECTION_AEC_RAMX_BACKUP_SIZE) 
#define AEC_CONSTANTX_START		 (AEC_CODE_START + 1*SECTION_AEC_CODE_SIZE) 

#define SPEECH_RAMY_BACKUP_START		 (AEC_CONSTANTX_START + 1*SECTION_AEC_CONSTANTX_SIZE) 
#define MORPH_CONSTY_START		 (SPEECH_RAMY_BACKUP_START + 1*SECTION_SPEECH_RAMY_BACKUP_SIZE) 
#define MORPH_CODE_START		 (MORPH_CONSTY_START + 1*SECTION_MORPH_CONSTY_SIZE) 

#define G_RXBUF_START		 (MORPH_CODE_START + 1*SECTION_MORPH_CODE_SIZE) 
#define G_TXBUF_START		 (G_RXBUF_START + 1*G_RXBUF_SIZE) 

#define G_BLUETOOTH_RXBUF_START (G_TXBUF_START + 1*G_RXBUF_SIZE)
#define G_BLUETOOTH_TXBUF_START (G_BLUETOOTH_RXBUF_START + 1*G_RXBUF_SIZE)



#define  PC_START               0x4//0x0  
 
