#ifndef MAP_EXPORT_H
#define MAP_EXPORT_H

/* This file defines the addresses of exported variables.
   It's created by voc_map automatically.*/

#define VPP_SPEECH_DEC_IN_STRUCT                	(0 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_ENC_OUT_STRUCT               	(26 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_ENC_IN_STRUCT                	(48 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_DEC_OUT_STRUCT               	(368 + RAM_X_BEGIN_ADDR)
#define GLOBAL_NOTCH_FILTER_COEF_ADDR           	(7000 + RAM_X_BEGIN_ADDR)
#define VPP_SPEECH_INIT_STRUCT                  	(0 + RAM_Y_BEGIN_ADDR)
#define VPP_SPEECH_AUDIO_CFG_STRUCT             	(56 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_DIGITAL_GAIN_ADDR            	(386 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_DIGITAL_MAXVALUE_ADDR        	(387 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_DIGITAL_GAIN_ADDR       	(388 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_DIGITAL_MAXVALUE_ADDR   	(389 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_OUTPUTENERGY_ADDR                	(390 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_INPUTENERGY_ADDR                 	(392 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_SPEAKER_GAIN_ADDR	(552 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISE_SUPPRESS_LEAK_ESTIMATE_ADDR	(553 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_RAMX_BACKUP_ADDR          	(554 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_CODE_BACKUP_ADDR          	(556 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_RAMX_BACKUP_ADDR             	(558 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CODE_ADDR                    	(560 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_CONSTX_ADDR                  	(562 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RX_ADDR                          	(564 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_TX_ADDR                          	(566 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CODE_ADDR          	(568 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_NOISESUPPRESS_CONSTX_ADDR        	(570 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MIC_NOISESUPPRESS_RAMX_BACKUP_ADDR	(572 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_RECEIVER_NOISESUPPRESS_RAMX_BACKUP_ADDR	(574 + RAM_Y_BEGIN_ADDR)
#define m_AECProcPara_ADDR                      	(576 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_SPEECH_RECORD_FLAG               	(627 + RAM_Y_BEGIN_ADDR)
#define MORPHVOICE_ENABLE_FLAG_ADDR             	(630 + RAM_Y_BEGIN_ADDR)
#define PITCH_SHIFT_ADDR                        	(631 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_RX_ADDR                	(632 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_BLUETOOTH_TX_ADDR                	(634 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_HANDLE_FLAG   	(8940 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_EXTERN_PROCESS_MIC_ENABLE_FLAG   	(8941 + RAM_Y_BEGIN_ADDR)
#define HIGH_PASS_FILTER_ENABLE_FLAG_ADDR       	(8942 + RAM_Y_BEGIN_ADDR)
#define NOTCH_FILTER_ENABLE_FLAG_ADDR           	(8943 + RAM_Y_BEGIN_ADDR)
#define MIC_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR   	(8944 + RAM_Y_BEGIN_ADDR)
#define RECEIVER_NOISE_SUPPRESSER_ENABLE_FLAG_ADDR	(8945 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_MORPH_RAMX_BACKUP_ADDR           	(8948 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_GAIN_ADDR        	(8954 + RAM_Y_BEGIN_ADDR)
#define GLOBAL_AEC_SPK_DIGITAL_MAXVALUE_ADDR    	(8955 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_STRUCT              	(8956 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_FILTER_ROUND               	(9104 + RAM_Y_BEGIN_ADDR)
#define CVSD_DEC_OUTPUT_ROUND                   	(9106 + RAM_Y_BEGIN_ADDR)
#define CVSD_LOWPASS_DEC_ENC_FLAG               	(9108 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_delta                          	(9110 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_delta                          	(9112 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_min                          	(9114 + RAM_Y_BEGIN_ADDR)
#define CVSD_delta_max                          	(9116 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_min                              	(9118 + RAM_Y_BEGIN_ADDR)
#define CVSD_y_max                              	(9120 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_xest_l                         	(9122 + RAM_Y_BEGIN_ADDR)
#define CVSD_dec_xest_l                         	(9124 + RAM_Y_BEGIN_ADDR)
#define CVSD_ENC_JUDGE_alpha_buf                	(9126 + RAM_Y_BEGIN_ADDR)
#define CVSD_enc_first_frame_flag               	(9128 + RAM_Y_BEGIN_ADDR)
#define AEC_AF_CONV_TIME_STRUCT                 	(9168 + RAM_Y_BEGIN_ADDR)
#define NS_MIC_GAIN_ADDR                        	(9176 + RAM_Y_BEGIN_ADDR)

#endif
