##i ----------------------------------------------------------- ##
## Don't touch the next line unless you know what you're doing.##
## ----------------------------------------------------------- ##
include ${SOFT_WORKDIR}/env/compilation/compilevars.mk

# Name of the module
LOCAL_NAME := apps

# List of submodules which contain code we need to include in the final lib
LOCAL_MODULE_DEPENDS := \
                        apps/gui \
                        apps/system \
                        apps/ap_gui \
                        apps/ap_main \
                        apps/ap_music \
                        apps/ap_fm \
                        apps/ap_record \
                        apps/ap_calendar \
                        apps/ap_usbdisk \
                        apps/ap_setting\
                        apps/ap_idle\
                        apps/ap_linein\
                        apps/ap_charging \
                        apps/ap_bluetooth  
                        

# This is a top-level module
IS_TOP_LEVEL := yes

## ------------------------------------- ##
##  Do Not touch below this line         ##
## ------------------------------------- ##
include ${SOFT_WORKDIR}/env/compilation/compilerules.mk

