////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"
#include "chip_id.h"

#include "hal_map_engine.h"

#include "sx_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#define SX_VERSION_STRING "Hello, I'm SX!"
#include "sxp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================

// To avoid linkage issue while compiling platform_test programs,
// we put the definition here instead of in sap_main.c
#define SXS_UNCACHED_DATA __attribute__((section(".ucdata")))
VOLATILE UINT32 SXS_UNCACHED_DATA g_sxsDebugIdleHookEnable = 0;

// =============================================================================
// g_sxMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
PROTECTED HAL_MAP_VERSION_T g_sxMapVersion = SX_VERSION_STRUCT;



// =============================================================================
// g_sxMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED SX_MAP_ACCESS_T g_sxMapAccess =
{
    // Put your initialization here.
    .sxExternalTraceEnablePtr = NULL,
    .sxsDebugIdleHookEnablePtr = (UINT32*)&g_sxsDebugIdleHookEnable,
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// sx_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID sx_RegisterYourself(VOID)
{
    hal_MapEngineRegisterModule(HAL_MAP_ID_SX, &g_sxMapVersion, &g_sxMapAccess);
}

