////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//            Copyright (C) 2003-2007, Coolsand Technologies, Inc.            //
//                            All Rights Reserved                             //
//                                                                            //
//      This source code is the property of Coolsand Technologies and is      //
//      confidential.  Any  modification, distribution,  reproduction or      //
//      exploitation  of  any content of this file is totally forbidden,      //
//      except  with the  written permission  of  Coolsand Technologies.      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
/// @file                                                                     //
/// That file Implements the functions to register the module.
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "cs_types.h"

#include "hal_map_engine.h"

#include "memd_map.h"



// =============================================================================
//  MACROS
// =============================================================================

#ifdef MEMD_USE_ROMULATOR
#define MEMD_VERSION_STRING "MEMD for Romulator " STRINGIFY_VALUE(ROMU_VER) " emulating " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#else
#define MEMD_VERSION_STRING "MEMD for " STRINGIFY_VALUE(MEMD_FLSH_MODEL)
#endif
//#include "memdp_version.h"



// =============================================================================
//  GLOBAL VARIABLES
// =============================================================================


// =============================================================================
// g_memdMapVersion
// -----------------------------------------------------------------------------
/// Contains the version of the module.
/// The macro used is generated by the make process.
// =============================================================================
//PROTECTED HAL_MAP_VERSION_T g_memdMapVersion = MEMD_VERSION_STRUCT;



// =============================================================================
// g_memdMapAccess
// -----------------------------------------------------------------------------
/// Contains the addresses of the structures of the module that will be
/// accessible from a remote PC (e.g. through CoolWatcher).
// =============================================================================
PROTECTED MEMD_MAP_ACCESS_T g_memdMapAccess =
{
    // Put your initialization here.
};



// =============================================================================
//  FUNCTIONS
// =============================================================================


// =============================================================================
// memd_RegisterYourself
// -----------------------------------------------------------------------------
/// This function registers the module itself to HAL so that the version and
/// the map accessor are filled. Then, the CSW get version function and the
/// CoolWatcher get version command will work.
// =============================================================================
PUBLIC VOID memd_RegisterYourself(VOID)
{
//    hal_MapEngineRegisterModule(HAL_MAP_ID_MEMD, &g_memdMapVersion, &g_memdMapAccess);
}
